// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPZs7e-cdy-htJgxAG0B1hFh1KEZKiFIU',
    appId: '1:358595115637:web:956180762b72beaa8cd63c',
    messagingSenderId: '358595115637',
    projectId: 'flutterfirebasetasks',
    authDomain: 'flutterfirebasetasks.firebaseapp.com',
    storageBucket: 'flutterfirebasetasks.appspot.com',
    measurementId: 'G-GMFT5HPE7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8eOnQej_x1Mtvujc6NrjnknoX0QS8EjU',
    appId: '1:358595115637:android:5ebbfd62044acdf88cd63c',
    messagingSenderId: '358595115637',
    projectId: 'flutterfirebasetasks',
    storageBucket: 'flutterfirebasetasks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxSYkadK5VVM-USXu0zSBWmXXeN7Muv-g',
    appId: '1:358595115637:ios:f6d5c9c63db786de8cd63c',
    messagingSenderId: '358595115637',
    projectId: 'flutterfirebasetasks',
    storageBucket: 'flutterfirebasetasks.appspot.com',
    iosBundleId: 'com.example.trackTrail2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxSYkadK5VVM-USXu0zSBWmXXeN7Muv-g',
    appId: '1:358595115637:ios:f6d5c9c63db786de8cd63c',
    messagingSenderId: '358595115637',
    projectId: 'flutterfirebasetasks',
    storageBucket: 'flutterfirebasetasks.appspot.com',
    iosBundleId: 'com.example.trackTrail2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPZs7e-cdy-htJgxAG0B1hFh1KEZKiFIU',
    appId: '1:358595115637:web:b9a6a763b54199928cd63c',
    messagingSenderId: '358595115637',
    projectId: 'flutterfirebasetasks',
    authDomain: 'flutterfirebasetasks.firebaseapp.com',
    storageBucket: 'flutterfirebasetasks.appspot.com',
    measurementId: 'G-9LNF6RQYCY',
  );
}
